<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Data Science and AI
## Lab 7.1.1: Decision Trees

INSTRUCTIONS:

- Read the guides and hints, then create the necessary analysis and code for the scenario below.
- The baseline results (minimum) are:
    - **Accuracy** = 0.6895
    - **ROC AUC**  = 0.5690
- Try to achieve better results!

# Foreword
It is common that companies and professionals start with the data immediately available. Although this approach works, ideally the first step is to identify the problem or question and only then identify and obtain the set of data that can help to solve or answer the problem.

Also, given the current abundance of data, processing power and some particular machine learning methods, there could be a temptation to use ALL the data available. **Quality** is _**better**_ than **Quantity**!

Part of calling this discipline **Data Science** is that it is supposed to follow a process and not reach conclusions without support from evidence.

Moreover, it is a creative, exploratory, labourious and iterative process. It is part of the process to repeat, review and change when finding a dead-end.

# Step 1: Define the problem or question
Identify the subject matter and the given or obvious questions that would be relevant in the field.

## Potential Questions
List the given or obvious questions.
Is this guy going to donate blood in march 2007 or not?
## Actual Question
Choose the **one** question that should be answered.
Is this guy going to donate blood in march 2007 or not?

In [22]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# Step 2: Find the Data
### Blood Transfusion Service Center DataSet
- **Abstract**: Data taken from the **Blood Transfusion Service Center** in Hsin-Chu City in Taiwan.
- Date Donated: 2008-10-03
- Source:
        Original Owner and Donor: Prof. I-Cheng Yeh
        Department of Information Management
        Chung-Hua University,
        Hsin Chu, Taiwan 30067, R.O.C.

- Citation Request:
    **NOTE**: Reuse of this database is unlimited with retention of copyright notice for Prof. I-Cheng Yeh and the following published paper:

        Yeh, I-Cheng, Yang, King-Jang, and Ting, Tao-Ming, "Knowledge discovery on RFM model using Bernoulli sequence, "Expert Systems with Applications, 2008
        
### UCI - Machine Learning Repository
- Center for Machine Learning and Intelligent Systems

The [**UCI Machine Learning Repository**](https://archive.ics.uci.edu/ml/datasets/Blood+Transfusion+Service+Center) is a collection of databases, domain theories, and data generators that are used by the machine learning community for the empirical analysis of machine learning algorithms.

In [9]:
blood= pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/blood-transfusion/transfusion.data")

# Step 3: Read the Data
- Read the data
- Perform some basic structural cleaning to facilitate the work

# Step 4: Explore and Clean the Data
- Perform some initial simple **EDA** (Exploratory Data Analysis)
- Check for
    - **Number of features**
    - **Data types**
    - **Domains, Intervals**
    - **Outliers** (are they valid or spurious data [read or measure errors])
    - **Null** (values not present or coded [as zero of empty strings])
    - **Missing Values** (coded [as zero of empty strings] or values not present)
    - **Coded content** (classes identified by numbers or codes to represent absence of data)

In [4]:
blood.head()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2,50,12500,98,1
1,0,13,3250,28,1
2,1,16,4000,35,1
3,2,20,5000,45,1
4,1,24,6000,77,0

In [5]:
blood.describe()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
count,748.000000,748.000000,748.000000,748.000000,748.000000
mean,9.506684,5.514706,1378.676471,34.282086,0.237968
std,8.095396,5.839307,1459.826781,24.376714,0.426124
min,0.000000,1.000000,250.000000,2.000000,0.000000
25%,2.750000,2.000000,500.000000,16.000000,0.000000
50%,7.000000,4.000000,1000.000000,28.000000,0.000000
75%,14.000000,7.000000,1750.000000,50.000000,0.000000
max,74.000000,50.000000,12500.000000,98.000000,1.000000

In [6]:
blood.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Recency (months)                            748 non-null    int64
 1   Frequency (times)                           748 non-null    int64
 2   Monetary (c.c. blood)                       748 non-null    int64
 3   Time (months)                               748 non-null    int64
 4   whether he/she donated blood in March 2007  748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB

In [7]:
blood.isnull().sum()

Recency (months)                              0
Frequency (times)                             0
Monetary (c.c. blood)                         0
Time (months)                                 0
whether he/she donated blood in March 2007    0
dtype: int64

# Step 5: Prepare the Data
- Deal with the data as required by the modelling technique
    - **Outliers** (remove or adjust if possible or necessary)
    - **Null** (remove or interpolate if possible or necessary)
    - **Missing Values** (remove or interpolate if possible or necessary)
    - **Coded content** (transform if possible or necessary [str to number or vice-versa])
    - **Feature Engineer** (if useful or necessary)

NameError: name 'train_test_split' is not defined

NameError: name 'X' is not defined

# Step 6: Modelling
Refer to the Problem and Main Question.
- What are the input variables (features)?
- Is there an output variable (label)?
- If there is an output variable:
    - What is it?
    - What is its type?
- What type of Modelling is it?
    - [ ] Supervised
    - [ ] Unsupervised
- What type of Modelling is it?
    - [ ] Regression
    - [ ] Classification (binary)
    - [ ] Classification (multi-class)
    - [ ] Clustering

In [1]:
X = blood[['Recency (months)', 'Frequency (times)', 'Monetary (c.c. blood)', 'Time (months)']]
y = blood['whether he/she donated blood in March 2007']

NameError: name 'blood' is not defined

# Step 7: Split the Data

Need to check for **Supervised** modelling:
- Number of known cases or observations
- Define the split in Training/Test or Training/Validation/Test and their proportions
- Check for unbalanced classes and how to keep or avoid it when splitting

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Step 8: Define a Model

Define the model and its hyper-parameters.

Consider the parameters and hyper-parameters of each model at each (re)run and after checking the efficiency of a model against the training and test datasets.

ValueError: Expected 2D array, got 1D array instead:
array=[ 9.  3.  3.  3.  6.  1.  5.  4. 11. 11.  3. 11.  5.  1.  7.  2.  1.  1.
  6.  2.  9.  1. 21.  4.  8.  6.  3.  8.  5.  1.  1.  4.  4.  4.  9.  5.
  2.  1.  5.  5. 10.  1.  3. 14.  3.  4. 11.  1.  4.  3.  1. 12. 11.  3.
  3.  1.  1.  8.  2.  6.  1.  2. 16.  1.  1.  5. 12. 15.  5.  1.  2.  7.
  3.  1.  1.  4.  3.  3.  5.  5.  1. 16.  6.  3.  6.  1.  3.  5.  6. 13.
  7.  2.  1.  5.  8.  8.  1.  4. 12.  1.  3.  5.  8. 46.  2.  6.  1.  7.
  7.  1.  2.  5.  7.  1.  2.  7.  6.  5.  5.  8.  2. 24.  1.  2.  4.  3.
  7.  2. 15.  7.  3.  2.  3. 11.  5.  1.  3.  4. 50.  4.  2.  4.  3. 18.
  1.  7.  1.  1.  2.  5.  9. 14.  2.  3.  6.  3. 11.  7.  6.  3.  5.  9.
 14.  5.  1.  9.  5.  6.  2.  6.  8.  2.  3. 14. 10.  3.  6.  3.  8.  8.
  2.  4.  1.  8.  9. 44.  1.  1.  1.  1.  5.  2.  1.  3.  3. 14.  1. 16.
  3.  1.  1.  9.  7. 10.  5.  4. 14.  5.  1. 14.  3.  5.  2.  4.  2.  2.
  2.  1.  8.  4. 38.  2.  8.  4.  1. 16.  2.  7. 16.  1. 16. 15.  1.  4.
  3.  2.  8.  3.  7. 24.  3.  2. 11.  4.  2.  3.  6. 10.  3.  5.  1.  4.
  1.  9.  1. 19.  1. 14.  2.  2.  4. 20.  8.  4.  2.  7.  2.  3.  2. 17.
  2.  6.  1.  6.  1.  3.  3. 11.  6.  1.  6.  1.  2.  3.  4.  2.  2.  2.
  3. 10. 16.  4.  1.  2.  7.  2. 43.  5.  5.  3.  6.  5.  2.  3.  1.  1.
 12. 10.  1.  3. 11.  5.  2.  1. 10. 16. 11. 10.  6.  9.  1.  4.  3.  5.
  2.  2. 11. 12.  6.  3.  1.  7.  9.  5.  9.  7. 12.  2.  3.  3.  2.  1.
 12.  2.  2.  1.  7. 11.  1.  2.  2.  3.  7.  1.  4.  1.  1.  2.  5.  5.
  5.  3.  6.  6.  8.  5.  2.  6. 12.  2. 14. 12.  1.  3.  2.  8.  1.  1.
  1.  3.  6.  2.  8.  1.  1. 13.  8.  1.  3.  1.  5.  1.  1.  4.  8. 11.
  4.  1.  1.  2.  3.  5.  5.  1.  1.  6.  1.  3.  1. 41.  1.  1. 14.  4.
  2.  6.  9.  6.  3.  1.  9.  8.  6.  1.  8.  3.  1.  7. 10.  8.  2.  1.
  3.  2.  2.  2.  3. 15.  1. 24.  1.  1. 14.  4.  2.  1. 34.  2. 10.  6.
 11. 12.  3.  1.  3.  1.  5.  1.  4.  3.  1.  5. 10.  3.  2.  8.  1. 11.
  3.  6.  1. 13.  4.  1.  4.  1.  6.  7.  4.  6.  1.  1.  3.  4.  7.  1.
  4.  5.  6. 17.  9.  7. 13.  3.  9.  6.  6. 16. 21.  5.  1. 15.  2.  3.
 14.  1. 22. 13.  2.  2.  1.  5.  1.  7.  2.  1.  2. 26. 17.  6. 16.  7.
  5.  2.  5.  2.  4. 16.  2. 11.  8. 11.  1.  1.  1. 13.  7.  7.  4.  3.
  1.  4.  2.  5.  8.  7.  2.  2.  1.  7.  1.  4.  5.  1.  3.  3.  4.  8.
 11.  7.  9.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

# Step 9: Fit the Model

In [20]:
clf = DecisionTreeClassifier(max_leaf_nodes=3, random_state=42)
clf.fit(X_train, y_train)
clft.fit(X_test, y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[ 9.  3.  3.  3.  6.  1.  5.  4. 11. 11.  3. 11.  5.  1.  7.  2.  1.  1.
  6.  2.  9.  1. 21.  4.  8.  6.  3.  8.  5.  1.  1.  4.  4.  4.  9.  5.
  2.  1.  5.  5. 10.  1.  3. 14.  3.  4. 11.  1.  4.  3.  1. 12. 11.  3.
  3.  1.  1.  8.  2.  6.  1.  2. 16.  1.  1.  5. 12. 15.  5.  1.  2.  7.
  3.  1.  1.  4.  3.  3.  5.  5.  1. 16.  6.  3.  6.  1.  3.  5.  6. 13.
  7.  2.  1.  5.  8.  8.  1.  4. 12.  1.  3.  5.  8. 46.  2.  6.  1.  7.
  7.  1.  2.  5.  7.  1.  2.  7.  6.  5.  5.  8.  2. 24.  1.  2.  4.  3.
  7.  2. 15.  7.  3.  2.  3. 11.  5.  1.  3.  4. 50.  4.  2.  4.  3. 18.
  1.  7.  1.  1.  2.  5.  9. 14.  2.  3.  6.  3. 11.  7.  6.  3.  5.  9.
 14.  5.  1.  9.  5.  6.  2.  6.  8.  2.  3. 14. 10.  3.  6.  3.  8.  8.
  2.  4.  1.  8.  9. 44.  1.  1.  1.  1.  5.  2.  1.  3.  3. 14.  1. 16.
  3.  1.  1.  9.  7. 10.  5.  4. 14.  5.  1. 14.  3.  5.  2.  4.  2.  2.
  2.  1.  8.  4. 38.  2.  8.  4.  1. 16.  2.  7. 16.  1. 16. 15.  1.  4.
  3.  2.  8.  3.  7. 24.  3.  2. 11.  4.  2.  3.  6. 10.  3.  5.  1.  4.
  1.  9.  1. 19.  1. 14.  2.  2.  4. 20.  8.  4.  2.  7.  2.  3.  2. 17.
  2.  6.  1.  6.  1.  3.  3. 11.  6.  1.  6.  1.  2.  3.  4.  2.  2.  2.
  3. 10. 16.  4.  1.  2.  7.  2. 43.  5.  5.  3.  6.  5.  2.  3.  1.  1.
 12. 10.  1.  3. 11.  5.  2.  1. 10. 16. 11. 10.  6.  9.  1.  4.  3.  5.
  2.  2. 11. 12.  6.  3.  1.  7.  9.  5.  9.  7. 12.  2.  3.  3.  2.  1.
 12.  2.  2.  1.  7. 11.  1.  2.  2.  3.  7.  1.  4.  1.  1.  2.  5.  5.
  5.  3.  6.  6.  8.  5.  2.  6. 12.  2. 14. 12.  1.  3.  2.  8.  1.  1.
  1.  3.  6.  2.  8.  1.  1. 13.  8.  1.  3.  1.  5.  1.  1.  4.  8. 11.
  4.  1.  1.  2.  3.  5.  5.  1.  1.  6.  1.  3.  1. 41.  1.  1. 14.  4.
  2.  6.  9.  6.  3.  1.  9.  8.  6.  1.  8.  3.  1.  7. 10.  8.  2.  1.
  3.  2.  2.  2.  3. 15.  1. 24.  1.  1. 14.  4.  2.  1. 34.  2. 10.  6.
 11. 12.  3.  1.  3.  1.  5.  1.  4.  3.  1.  5. 10.  3.  2.  8.  1. 11.
  3.  6.  1. 13.  4.  1.  4.  1.  6.  7.  4.  6.  1.  1.  3.  4.  7.  1.
  4.  5.  6. 17.  9.  7. 13.  3.  9.  6.  6. 16. 21.  5.  1. 15.  2.  3.
 14.  1. 22. 13.  2.  2.  1.  5.  1.  7.  2.  1.  2. 26. 17.  6. 16.  7.
  5.  2.  5.  2.  4. 16.  2. 11.  8. 11.  1.  1.  1. 13.  7.  7.  4.  3.
  1.  4.  2.  5.  8.  7.  2.  2.  1.  7.  1.  4.  5.  1.  3.  3.  4.  8.
 11.  7.  9.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

# Step 10: Verify and Evaluate the Training Model
- Use the **training** data to make predictions
- What metrics are appropriate for the modelling approach used
- For **Supervised** models:
    - Check the **Training Results** with the **Training Predictions** during development
- Analyse, modify the parameters and hyper-parameters and repeat (within reason) until the model does not improve

In [21]:
clf.predict(X, check_input=True)
clf.score(X, y, sample_weight=None)

NameError: name 'predict' is not defined

# Step 11: Make Predictions and Evaluate the Test Model
**NOTE**: **Do this only after not making any more improvements in the model**.

- Use the **test** data to make predictions
- For **Supervised** models:
    - Check the **Test Results** with the **Test Predictions**

In [ ]:
clft.predict(X, check_input=True)
clft.score(X, y, sample_weight=None)

# Step 12: Solve the Problem or Answer the Question
The results of an analysis or modelling can be used:
- As part of a product or process, so the model can make predictions when new input data is available
- As part of a report including text and charts to help understand the problem
- As input for further questions



---



---



> > > > > > > > > © 2024 Institute of Data


---



---